// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./HomePage/Navbar";
import Footer from "./HomePage/Footer";
import CTA from "./HomePage/CTA";


export const metadata = {
  title: "Stack360 | Code Beyond Limits",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="icon.svg" type="image/x-icon" />
        <title>Stack360 | Code Beyond Limits</title>
      </head>
      <body className={`antialiased`}>
        <Navbar/>
        {children}
        <CTA/>
        <Footer/>
      </body>
    </html>
  );
}
